"""seed_prestataires.py
Insère 100+ prestataires de services dans la base PostgreSQL."""

import psycopg2
import os
from dotenv import load_dotenv

load_dotenv()

# Connexion à la base de données via la variable d'environnement
conn = psycopg2.connect(os.getenv("DATABASE_URL"))
cur = conn.cursor()

PRESTATAIRES = [
    # ═══════════════ PLOMBIERS ═══════════════
    ("Kouassi", "Jean-Baptiste", "plombier", "plomberie générale", "Abidjan", "Cocody",
     "+225 07 11 22 33", "+225 07 11 22 33",
     "Plombier professionnel avec 10 ans d'expérience. Fuite d'eau, installation sanitaire, débouchage, chauffe-eau. Intervention rapide 7j/7.",
     10, 15000, 80000, "par intervention", 4.8, 47, True,
     ["Cocody", "Plateau", "Deux-Plateaux", "Riviera"], ["Français", "Dioula"], True),
    ("Diallo", "Mamadou", "plombier", "débouchage et urgences", "Abidjan", "Yopougon",
     "+225 05 44 55 66", "+225 05 44 55 66",
     "Spécialiste débouchage canalisation et urgences plomberie. Disponible 24h/24. Devis gratuit.",
     7, 10000, 50000, "par intervention", 4.5, 32, True,
     ["Yopougon", "Adjamé", "Abobo"], ["Français", "Malinké"], False),
    ("Bamba", "Seydou", "plombier", "installation sanitaire", "Abidjan", "Marcory",
     "+225 01 77 88 99", "+225 01 77 88 99",
     "Installation complète salle de bain, cuisine. Pose baignoire, douche, WC, évier. Travail soigné et garantie 6 mois.",
     12, 20000, 150000, "par projet", 4.9, 61, True,
     ["Marcory", "Treichville", "Port-Bouët", "Zone 4"], ["Français"], True),
    ("Koné", "Ibrahim", "plombier", "plomberie générale", "Bouaké", "Centre",
     "+225 07 22 33 44", "+225 07 22 33 44",
     "Plombier à Bouaké. Réparation fuite, installation robinetterie, chauffe-eau solaire. 8 ans d'expérience.",
     8, 10000, 60000, "par intervention", 4.3, 18, True,
     ["Bouaké Centre", "Koko", "Belleville"], ["Français", "Dioula"], False),
    ("Ouattara", "Lassina", "plombier", "plomberie générale", "Yamoussoukro", "Centre",
     "+225 05 33 44 55", "+225 05 33 44 55",
     "Plombier certifié à Yamoussoukro. Tous travaux plomberie, sanitaire et évacuation.",
     6, 12000, 70000, "par intervention", 4.1, 12, True,
     ["Yamoussoukro", "Morofé"], ["Français", "Baoulé"], False),
    
    # ═══════════════ ÉLECTRICIENS ═══════════════
    ("Assi", "Koffi", "electricien", "installation électrique", "Abidjan", "Plateau",
     "+225 07 55 66 77", "+225 07 55 66 77",
     "Électricien diplômé. Installation tableau électrique, câblage, dépannage panne, climatisation, groupe électrogène. Devis gratuit.",
     15, 20000, 200000, "par projet", 4.9, 89, True,
     ["Plateau", "Cocody", "Deux-Plateaux", "Marcory", "Treichville"], ["Français"], True),
    ("Touré", "Adama", "electricien", "dépannage et urgences", "Abidjan", "Abobo",
     "+225 01 88 99 00", "+225 01 88 99 00",
     "Électricien disponible 24h/24 pour dépannage urgent. Panne courant, court-circuit, remplacement fusibles. Intervention rapide.",
     5, 10000, 40000, "par intervention", 4.2, 25, True,
     ["Abobo", "Adjamé", "Yopougon"], ["Français", "Dioula"], False),
    ("N'Goran", "Etienne", "electricien", "installation et rénovation", "Abidjan", "Cocody",
     "+225 07 66 77 88", "+225 07 66 77 88",
     "Électricien pour villas et appartements. Rénovation installation électrique, domotique, éclairage LED, panneaux solaires.",
     18, 30000, 500000, "par projet", 5.0, 103, True,
     ["Cocody", "Riviera", "Deux-Plateaux", "Angré"], ["Français", "Anglais"], True),
    ("Coulibaly", "Moussa", "electricien", "électricité générale", "Bouaké", "Koko",
     "+225 05 99 00 11", "+225 05 99 00 11",
     "Électricien à Bouaké. Installation, dépannage, câblage maison et commerce. Tarifs compétitifs.",
     9, 15000, 100000, "par projet", 4.4, 29, True,
     ["Bouaké", "Koko", "N'Gattakro"], ["Français", "Dioula"], False),
    ("Yao", "Narcisse", "electricien", "solaire et énergie", "Abidjan", "Marcory",
     "+225 07 11 00 22", "+225 07 11 00 22",
     "Spécialiste énergie solaire et groupes électrogènes. Installation panneaux solaires, batteries, onduleurs. Économisez sur votre facture.",
     10, 50000, 1000000, "par projet", 4.7, 44, True,
     ["Marcory", "Port-Bouët", "Koumassi", "Treichville"], ["Français"], True),
     
    # ═══════════════ MAÇONS ═══════════════
    ("Traoré", "Bakary", "macon", "construction et rénovation", "Abidjan", "Yopougon",
     "+225 05 22 33 44", "+225 05 22 33 44",
     "Maçon expérimenté. Construction villa, rénovation, carrelage, enduit, peinture. Équipe de 5 ouvriers qualifiés. Devis gratuit sur place.",
     20, 30000, 5000000, "par projet", 4.6, 78, True,
     ["Yopougon", "Abobo", "Adjamé", "Anyama"], ["Français", "Malinké", "Dioula"], True),
    ("Sanogo", "Drissa", "macon", "petits travaux", "Abidjan", "Treichville",
     "+225 07 33 44 55", "+225 07 33 44 55",
     "Maçon pour petits travaux : fissures, enduit, rebouchage, pose carrelage, réparation mur. Rapide et propre.",
     8, 15000, 200000, "par projet", 4.3, 31, True,
     ["Treichville", "Marcory", "Port-Bouët"], ["Français"], False),
    ("Diabaté", "Souleymane", "macon", "construction neuve", "Bouaké", "Belleville",
     "+225 01 44 55 66", "+225 01 44 55 66",
     "Entrepreneur maçonnerie à Bouaké. Construction maisons, immeubles, clôtures. Équipe complète, matériaux fournis si demandé.",
     25, 100000, 10000000, "par projet", 4.8, 52, True,
     ["Bouaké", "Belleville", "Air France"], ["Français", "Dioula"], True),
    ("Kra", "Paul", "macon", "rénovation et finition", "Abidjan", "Cocody",
     "+225 07 55 66 77", "+225 07 55 66 77",
     "Maçon spécialisé rénovation haut de gamme. Salle de bain, cuisine, terrasse. Finitions parfaites, délais respectés.",
     14, 50000, 2000000, "par projet", 4.9, 67, True,
     ["Cocody", "Riviera", "Deux-Plateaux", "Angré"], ["Français"], True),
    ("Fofana", "Lacina", "macon", "maçonnerie générale", "Yamoussoukro", "Morofé",
     "+225 05 66 77 88", "+225 05 66 77 88",
     "Maçon à Yamoussoukro. Construction, réparation, enduit, carrelage. Devis gratuit.",
     11, 20000, 500000, "par projet", 4.2, 19, True,
     ["Yamoussoukro", "Morofé", "Dokui"], ["Français", "Baoulé"], False),
     
    # ═══════════════ MENUISIERS ═══════════════
    ("Konaté", "Yacouba", "menuisier", "menuiserie bois", "Abidjan", "Adjamé",
     "+225 07 77 88 99", "+225 07 77 88 99",
     "Menuisier ébéniste. Fabrication portes, fenêtres, meubles sur mesure, cuisine équipée, dressing. Bois massif et contreplaqué.",
     16, 50000, 3000000, "par projet", 4.7, 88, True,
     ["Adjamé", "Plateau", "Cocody", "Yopougon"], ["Français", "Dioula"], True),
    ("Soro", "Gnénéman", "menuisier", "menuiserie aluminium", "Abidjan", "Marcory",
     "+225 01 88 99 00", "+225 01 88 99 00",
     "Spécialiste menuiserie aluminium et PVC. Fenêtres, portes, vérandas, garde-corps, moustiquaires. Pose et fabrication.",
     12, 40000, 2000000, "par projet", 4.5, 43, True,
     ["Marcory", "Treichville", "Port-Bouët", "Koumassi"], ["Français"], False),
    ("Gbagbo", "Hyppolite", "menuisier", "meubles sur mesure", "Abidjan", "Yopougon",
     "+225 07 99 00 11", "+225 07 99 00 11",
     "Fabrication meubles sur mesure : armoires, bibliothèques, tables, chaises, cuisines. Livraison et installation incluses.",
     9, 30000, 1500000, "par projet", 4.6, 55, True,
     ["Yopougon", "Abobo", "Adjamé"], ["Français", "Bété"], True),
    ("Dago", "Rémi", "menuisier", "menuiserie générale", "Bouaké", "Centre",
     "+225 05 00 11 22", "+225 05 00 11 22",
     "Menuisier à Bouaké. Toutes fabrications bois : portes, fenêtres, meubles. Devis sur place.",
     7, 25000, 800000, "par projet", 4.3, 22, True,
     ["Bouaké Centre", "Koko"], ["Français", "Dioula"], False),
     
    # ═══════════════ PEINTRES ═══════════════
    ("Aka", "Germain", "peintre", "peinture intérieure", "Abidjan", "Cocody",
     "+225 07 11 22 33", "+225 07 11 22 33",
     "Peintre professionnel. Peinture intérieure et extérieure, enduit, ravalement de façade. Travail soigné, délais respectés.",
     13, 15000, 500000, "par projet", 4.8, 92, True,
     ["Cocody", "Plateau", "Deux-Plateaux", "Marcory", "Treichville"], ["Français"], True),
    ("Wattara", "Aboubakar", "peintre", "peinture décorative", "Abidjan", "Marcory",
     "+225 05 33 44 55", "+225 05 33 44 55",
     "Peintre décorateur. Effets décoratifs, stucco, trompe-l'œil, faux-bois, tags artistiques. Transformez vos espaces.",
     10, 30000, 800000, "par projet", 4.9, 61, True,
     ["Marcory", "Cocody", "Plateau", "Zone 4"], ["Français"], True),
    ("Diomandé", "Sekou", "peintre", "peinture générale", "Yopougon", "Yopougon",
     "+225 07 44 55 66", "+225 07 44 55 66",
     "Peintre à Yopougon. Appartements, villas, commerces. Prix abordables, matériaux fournis sur demande.",
     6, 10000, 300000, "par projet", 4.2, 28, True,
     ["Yopougon", "Abobo", "Adjamé"], ["Français", "Dioula"], False),
    ("Aholi", "Bernard", "peintre", "peinture et ravalement", "Bouaké", "Koko",
     "+225 01 55 66 77", "+225 01 55 66 77",
     "Peintre à Bouaké. Intérieur, extérieur, ravalement façade. Devis gratuit. Équipe de 3 peintres.",
     15, 15000, 400000, "par projet", 4.4, 35, True,
     ["Bouaké", "Koko", "Belleville"], ["Français"], False),
     
    # ═══════════════ CARRELEURS ═══════════════
    ("Brou", "Félix", "carreleur", "pose carrelage", "Abidjan", "Treichville",
     "+225 07 66 77 88", "+225 07 66 77 88",
     "Carreleur professionnel. Pose carrelage sol et mur, faïence, mosaïque. Salle de bain, cuisine, terrasse. Travail précis et soigné.",
     11, 5000, 50000, "par m²", 4.7, 76, True,
     ["Treichville", "Marcory", "Port-Bouët", "Koumassi"], ["Français"], True),
    ("Kouamé", "Théodore", "carreleur", "carrelage et revêtement", "Abidjan", "Cocody",
     "+225 05 77 88 99", "+225 05 77 88 99",
     "Spécialiste grand format et carreaux de ciment. Pose, joints, imperméabilisation. Haut de gamme sur mesure.",
     17, 8000, 80000, "par m²", 4.9, 113, True,
     ["Cocody", "Riviera", "Deux-Plateaux", "Angré"], ["Français"], True),
    ("Zoro", "Martial", "carreleur", "pose et rénovation", "Yopougon", "Yopougon",
     "+225 07 88 99 00", "+225 07 88 99 00",
     "Carreleur à Yopougon. Pose rapide et soignée. Dépose ancien carrelage, ragréage, pose neuve. Tarifs compétitifs.",
     8, 4000, 35000, "par m²", 4.3, 41, True,
     ["Yopougon", "Abobo", "Adjamé"], ["Français", "Dioula"], False),
     
    # ═══════════════ CLIMATISATION ═══════════════
    ("Atta", "Sébastien", "climatisation", "installation climatiseur", "Abidjan", "Plateau",
     "+225 07 99 00 11", "+225 07 99 00 11",
     "Technicien climatisation certifié. Installation, maintenance, réparation toutes marques : Samsung, LG, Daikin, Midea. Devis gratuit.",
     14, 25000, 300000, "par unité", 4.8, 84, True,
     ["Plateau", "Cocody", "Marcory", "Treichville", "Zone 4"], ["Français"], True),
    ("Lago", "Rodrigue", "climatisation", "maintenance et réparation", "Abidjan", "Yopougon",
     "+225 05 00 11 22", "+225 05 00 11 22",
     "Réparation et entretien climatiseurs. Nettoyage filtre, recharge gaz, remplacement pièces. Intervention rapide.",
     7, 15000, 80000, "par intervention", 4.5, 37, True,
     ["Yopougon", "Abobo", "Adjamé", "Anyama"], ["Français", "Dioula"], False),
    ("Anon", "Christian", "climatisation", "climatisation commerciale", "Abidjan", "Marcory",
     "+225 07 11 22 33", "+225 07 11 22 33",
     "Spécialiste climatisation industrielle et commerciale. VRV, split-system, climatisation centrale. Contrats de maintenance disponibles.",
     20, 100000, 5000000, "par projet", 4.9, 56, True,
     ["Marcory", "Plateau", "Zone 4", "Port-Bouët"], ["Français", "Anglais"], True),
     
    # ═══════════════ SERRURIERS ═══════════════
    ("Loba", "Victor", "serrurier", "serrurerie urgence", "Abidjan", "Cocody",
     "+225 07 22 33 44", "+225 07 22 33 44",
     "Serrurier disponible 24h/24. Ouverture porte claquée, changement serrure, blindage porte, installation coffre-fort. Intervention 30min.",
     10, 20000, 150000, "par intervention", 4.7, 69, True,
     ["Cocody", "Plateau", "Deux-Plateaux", "Riviera", "Angré"], ["Français"], True),
    ("Goba", "Aristide", "serrurier", "serrurerie et sécurité", "Abidjan", "Marcory",
     "+225 05 33 44 55", "+225 05 33 44 55",
     "Serrurier et systèmes de sécurité. Serrures haute sécurité, digicode, interphone, alarme. Particuliers et entreprises.",
     8, 25000, 200000, "par intervention", 4.6, 43, True,
     ["Marcory", "Treichville", "Port-Bouët", "Zone 4"], ["Français"], False),
     
    # ═══════════════ JARDINIERS ═══════════════
    ("Séri", "Pascal", "jardinier", "entretien jardin", "Abidjan", "Cocody",
     "+225 07 44 55 66", "+225 07 44 55 66",
     "Jardinier paysagiste. Taille haies, tonte pelouse, élagage arbres, création jardin, arrosage automatique. Contrats mensuels disponibles.",
     12, 20000, 200000, "par intervention", 4.8, 57, True,
     ["Cocody", "Riviera", "Deux-Plateaux", "Angré", "Bingerville"], ["Français"], True),
    ("Alla", "Ernest", "jardinier", "création et aménagement", "Abidjan", "Yopougon",
     "+225 01 55 66 77", "+225 01 55 66 77",
     "Création et aménagement espaces verts. Conception jardin, pose gazon, plantation, bassins. Transformez votre extérieur.",
     9, 30000, 500000, "par projet", 4.5, 31, True,
     ["Yopougon", "Anyama", "Abobo"], ["Français", "Dioula"], False),
     
    # ═══════════════ NETTOYAGE ═══════════════
    ("Kouadio", "Albertine", "nettoyage", "nettoyage maison", "Abidjan", "Cocody",
     "+225 07 66 77 88", "+225 07 66 77 88",
     "Service de nettoyage professionnel domicile. Ménage, lavage vitres, nettoyage four, réfrigérateur, salle de bain. Discret et efficace.",
     6, 10000, 50000, "par séance", 4.9, 142, True,
     ["Cocody", "Deux-Plateaux", "Riviera", "Plateau"], ["Français"], True),
    ("Aké", "Madeleine", "nettoyage", "nettoyage après travaux", "Abidjan", "Marcory",
     "+225 05 77 88 99", "+225 05 77 88 99",
     "Nettoyage après chantier et travaux. Déblayage gravats, dépoussiérage, nettoyage vitres et sols. Équipe rapide et complète.",
     8, 30000, 200000, "par chantier", 4.7, 68, True,
     ["Marcory", "Treichville", "Port-Bouët", "Koumassi", "Zone 4"], ["Français"], True),
    ("Sylla", "Fatoumata", "nettoyage", "nettoyage bureau", "Abidjan", "Plateau",
     "+225 07 88 99 00", "+225 07 88 99 00",
     "Entreprise de nettoyage bureaux et locaux commerciaux. Contrats journaliers, hebdomadaires, mensuels. Matériel professionnel.",
     10, 30000, 300000, "par mois", 4.8, 89, True,
     ["Plateau", "Cocody", "Marcory", "Treichville"], ["Français"], True),
    ("Touré", "Aminata", "nettoyage", "nettoyage et désinfection", "Yopougon", "Yopougon",
     "+225 01 99 00 11", "+225 01 99 00 11",
     "Nettoyage domicile et désinfection. Ménage régulier, grand nettoyage, désinfection COVID. Produits professionnels.",
     5, 8000, 40000, "par séance", 4.4, 38, True,
     ["Yopougon", "Abobo", "Adjamé"], ["Français", "Malinké"], False),
     
    # ═══════════════ DÉMÉNAGEMENT ═══════════════
    ("Bah", "Mamadou", "demenagement", "déménagement local", "Abidjan", "Adjamé",
     "+225 07 00 11 22", "+225 07 00 11 22",
     "Service déménagement avec camion. Démontage, emballage, transport, remontage meubles. Toute Abidjan et intérieur du pays. Assurance incluse.",
     11, 50000, 500000, "par déménagement", 4.7, 93, True,
     ["Abidjan", "Yamoussoukro", "Bouaké", "San-Pédro"], ["Français", "Peulh"], True),
    ("Diop", "Ousmane", "demenagement", "transport et déménagement", "Abidjan", "Yopougon",
     "+225 05 11 22 33", "+225 05 11 22 33",
     "Camionnette et camion disponibles pour déménagement, livraison meubles, transport marchandises. Rapide et soigneux.",
     7, 30000, 300000, "par déménagement", 4.5, 47, True,
     ["Yopougon", "Abobo", "Adjamé", "Anyama"], ["Français", "Wolof"], False),
     
    # ═══════════════ INFORMATIQUE ═══════════════
    ("Kassi", "Raoul", "informatique", "réparation ordinateur", "Abidjan", "Plateau",
     "+225 07 22 33 44", "+225 07 22 33 44",
     "Technicien informatique certifié. Réparation PC, Mac, laptop, récupération données, virus, réseau, installation logiciels. Domicile ou atelier.",
     12, 10000, 100000, "par intervention", 4.9, 127, True,
     ["Plateau", "Cocody", "Marcory", "Deux-Plateaux"], ["Français", "Anglais"], True),
    ("Yobouet", "Stéphane", "informatique", "réseau et sécurité", "Abidjan", "Cocody",
     "+225 05 33 44 55", "+225 05 33 44 55",
     "Réseau informatique et cybersécurité. Installation réseau WiFi, câblage RJ45, firewall, serveur, maintenance parc informatique entreprise.",
     15, 30000, 500000, "par projet", 4.8, 74, True,
     ["Cocody", "Plateau", "Marcory", "Zone 4"], ["Français", "Anglais"], True),
    ("Konan", "Franck", "informatique", "développement web", "Abidjan", "Deux-Plateaux",
     "+225 07 44 55 66", "+225 07 44 55 66",
     "Développeur web freelance. Création sites web, e-commerce, applications mobiles, SEO. Portfolio disponible sur demande.",
     8, 50000, 2000000, "par projet", 4.7, 52, True,
     ["Cocody", "Plateau", "Deux-Plateaux"], ["Français", "Anglais"], True),
    ("Gnahoua", "Didier", "informatique", "réparation téléphone", "Abidjan", "Adjamé",
     "+225 01 55 66 77", "+225 01 55 66 77",
     "Réparation smartphones et tablettes. Écran cassé, batterie, charge, logiciel. Toutes marques : iPhone, Samsung, Tecno, Itel. Pièces garanties.",
     6, 5000, 80000, "par réparation", 4.6, 198, True,
     ["Adjamé", "Plateau", "Abobo", "Yopougon"], ["Français", "Dioula"], False),
     
    # ═══════════════ COUTURE / TAILLEUR ═══════════════
    ("Coulibaly", "Mariam", "couture", "couture femme", "Abidjan", "Treichville",
     "+225 07 66 77 88", "+225 07 66 77 88",
     "Couturière créatrice. Robes soirée, tenues de mariage, uniformes, retouches. Pagne, ankara, wax. Délai 3-7 jours.",
     14, 5000, 150000, "par tenue", 4.9, 167, True,
     ["Treichville", "Marcory", "Port-Bouët", "Cocody"], ["Français", "Dioula"], True),
    ("Traoré", "Aissatou", "couture", "tailleur homme", "Abidjan", "Yopougon",
     "+225 05 77 88 99", "+225 05 77 88 99",
     "Tailleur homme et mixte. Costumes, boubous, chemises sur mesure, pantalons. Travail soigné, prise de mesure à domicile possible.",
     10, 8000, 80000, "par tenue", 4.7, 93, True,
     ["Yopougon", "Adjamé", "Abobo"], ["Français", "Malinké"], False),
    ("Bamba", "Kadiatou", "couture", "couture et broderie", "Bouaké", "Centre",
     "+225 07 88 99 00", "+225 07 88 99 00",
     "Couturière à Bouaké. Tenues traditionnelles, modernes, broderie. Spécialiste tenues de mariage et cérémonies.",
     8, 5000, 100000, "par tenue", 4.5, 44, True,
     ["Bouaké", "Koko", "Belleville"], ["Français", "Dioula", "Malinké"], False),
     
    # ═══════════════ COIFFEUR À DOMICILE ═══════════════
    ("Koffi", "Sandrine", "coiffeur", "coiffure femme domicile", "Abidjan", "Cocody",
     "+225 07 99 00 11", "+225 07 99 00 11",
     "Coiffeuse à domicile. Tresses, locks, perruques, défrisage, coloration, coiffure mariage. Se déplace chez vous. Sur rendez-vous.",
     8, 5000, 50000, "par prestation", 4.9, 213, True,
     ["Cocody", "Deux-Plateaux", "Riviera", "Angré", "Plateau"], ["Français"], True),
    ("Diallo", "Aïcha", "coiffeur", "tresses et locks", "Abidjan", "Adjamé",
     "+225 05 00 11 22", "+225 05 00 11 22",
     "Spécialiste tresses africaines, locks, nattes. À domicile ou en salon. Toutes techniques, toutes longueurs. Produits naturels.",
     12, 3000, 30000, "par prestation", 4.8, 189, True,
     ["Adjamé", "Abobo", "Yopougon", "Treichville"], ["Français", "Peulh", "Dioula"], True),
    ("Yao", "Prisca", "coiffeur", "coiffure homme domicile", "Abidjan", "Marcory",
     "+225 07 11 22 33", "+225 07 11 22 33",
     "Barbier à domicile. Coupe homme, barbe, rasage, soins cheveux. Dreadlocks, fade, coupe classique. Sur rendez-vous.",
     5, 3000, 15000, "par prestation", 4.7, 142, True,
     ["Marcory", "Treichville", "Port-Bouët", "Zone 4"], ["Français"], False),
     
    # ═══════════════ MÉCANICIEN ═══════════════
    ("Coulibaly", "Noumory", "mecanicien", "mécanique générale", "Abidjan", "Adjamé",
     "+225 07 22 33 44", "+225 07 22 33 44",
     "Mécanicien auto toutes marques. Vidange, freins, moteur, boîte de vitesse, climatisation voiture. Garage ou déplacement possible.",
     16, 10000, 500000, "par intervention", 4.7, 87, True,
     ["Adjamé", "Plateau", "Abobo", "Yopougon"], ["Français", "Dioula"], True),
    ("Touré", "Boubacar", "mecanicien", "mécanique automobile", "Abidjan", "Yopougon",
     "+225 05 33 44 55", "+225 05 33 44 55",
     "Mécanicien spécialisé véhicules asiatiques (Toyota, Mitsubishi, Honda). Diagnostic électronique, entretien, réparation moteur.",
     12, 15000, 400000, "par intervention", 4.5, 61, True,
     ["Yopougon", "Abobo", "Adjamé", "Anyama"], ["Français", "Malinké"], False),
    ("Kouassi", "Aimé", "mecanicien", "dépannage et remorquage", "Abidjan", "Cocody",
     "+225 07 44 55 66", "+225 07 44 55 66",
     "Mécanicien dépanneur. Panne sur route, remorquage, crevaison, batterie. Disponible 24h/24. Intervention rapide sur tout Abidjan.",
     9, 20000, 100000, "par intervention", 4.8, 103, True,
     ["Cocody", "Plateau", "Marcory", "Treichville", "Zone 4"], ["Français"], True),
    ("N'Guessan", "Serge", "mecanicien", "moto et scooter", "Abidjan", "Treichville",
     "+225 01 55 66 77", "+225 01 55 66 77",
     "Mécanicien spécialisé motos et scooters. Entretien, réparation, pièces détachées. Toutes marques : Yamaha, Honda, TVS, Bajaj.",
     8, 5000, 100000, "par intervention", 4.4, 74, True,
     ["Treichville", "Marcory", "Port-Bouët", "Koumassi"], ["Français"], False),
     
    # ═══════════════ TRAITEUR ═══════════════
    ("Kpan", "Evelyne", "traiteur", "cuisine ivoirienne", "Abidjan", "Cocody",
     "+225 07 66 77 88", "+225 07 66 77 88",
     "Traiteur cuisine ivoirienne. Mariages, baptêmes, anniversaires. Attiéké, kedjenou, foutou, sauce graine. Buffet 50 à 500 personnes.",
     15, 3000, 10000, "par personne", 4.9, 134, True,
     ["Cocody", "Plateau", "Deux-Plateaux", "Marcory"], ["Français"], True),
    ("Soumahoro", "Hawa", "traiteur", "cuisine africaine", "Abidjan", "Yopougon",
     "+225 05 77 88 99", "+225 05 77 88 99",
     "Traiteur cuisine africaine et internationale. Riz au gras, thiéboudiène, mafé, yassa. Livraison à domicile disponible.",
     10, 2000, 8000, "par personne", 4.7, 89, True,
     ["Yopougon", "Abobo", "Adjamé", "Anyama"], ["Français", "Dioula", "Malinké"], False),
    ("Boni", "Cécile", "traiteur", "pâtisserie et gâteaux", "Abidjan", "Marcory",
     "+225 07 88 99 00", "+225 07 88 99 00",
     "Pâtissière professionnelle. Gâteaux mariage, anniversaire, baptême. Wedding cake, macarons, entremets. Livraison Abidjan.",
     12, 30000, 500000, "par commande", 5.0, 176, True,
     ["Marcory", "Cocody", "Plateau", "Treichville", "Zone 4"], ["Français"], True),
    ("Gbané", "Marcelline", "traiteur", "chef à domicile", "Abidjan", "Deux-Plateaux",
     "+225 01 99 00 11", "+225 01 99 00 11",
     "Chef cuisinière à domicile. Dîners privés, repas d'affaires, cours de cuisine. Menus personnalisés, spécialités ivoiriennes et internationales.",
     8, 50000, 300000, "par événement", 4.9, 67, True,
     ["Deux-Plateaux", "Cocody", "Riviera", "Angré"], ["Français"], True),
     
    # ═══════════════ PRESTATAIRES SUPPLÉMENTAIRES PAR VILLE ═══════════════
    # San-Pédro
    ("Gohi", "Rodrigue", "plombier", "plomberie générale", "San-Pédro", "Centre",
     "+225 07 00 11 22", "+225 07 00 11 22",
     "Plombier à San-Pédro. Tous travaux plomberie, sanitaire. Intervention rapide.", 7, 10000, 60000,
     "par intervention", 4.2, 14, True, ["San-Pédro"], ["Français", "Bété"], False),
    ("Goh", "Théophile", "electricien", "électricité générale", "San-Pédro", "Centre",
     "+225 05 11 22 33", "+225 05 11 22 33",
     "Électricien à San-Pédro. Installation, dépannage, câblage. Particuliers et entreprises.", 9, 15000, 100000,
     "par projet", 4.3, 11, True, ["San-Pédro"], ["Français"], False),
     
    # Korhogo
    ("Silué", "Mamadou", "macon", "construction", "Korhogo", "Centre",
     "+225 07 22 33 44", "+225 07 22 33 44",
     "Maçon à Korhogo. Construction, rénovation, enduit. Équipe disponible.", 15, 20000, 1000000,
     "par projet", 4.4, 23, True, ["Korhogo"], ["Français", "Sénoufo"], False),
    ("Fofana", "Issa", "electricien", "électricité générale", "Korhogo", "Centre",
     "+225 05 33 44 55", "+225 05 33 44 55",
     "Électricien à Korhogo. Installation et dépannage. Disponible 7j/7.", 8, 15000, 120000,
     "par projet", 4.1, 16, True, ["Korhogo"], ["Français", "Dioula"], False),
     
    # Man
    ("Doua", "Gervais", "plombier", "plomberie générale", "Man", "Centre",
     "+225 07 44 55 66", "+225 07 44 55 66",
     "Plombier à Man. Fuite, installation, débouchage. Intervention rapide.", 6, 10000, 50000,
     "par intervention", 4.0, 9, True, ["Man"], ["Français", "Dan"], False),
    ("Zogbo", "Mathieu", "menuisier", "menuiserie bois", "Man", "Centre",
     "+225 01 55 66 77", "+225 01 55 66 77",
     "Menuisier à Man. Portes, fenêtres, meubles sur mesure. Bois de qualité.", 12, 30000, 800000,
     "par projet", 4.5, 18, True, ["Man"], ["Français", "Dan"], False),
     
    # Daloa
    ("Gnahoré", "Théodore", "electricien", "installation électrique", "Daloa", "Centre",
     "+225 07 66 77 88", "+225 07 66 77 88",
     "Électricien à Daloa. Tous travaux électriques, installation, dépannage. Devis gratuit.", 11, 15000, 150000,
     "par projet", 4.3, 21, True, ["Daloa"], ["Français", "Bété"], False),
    ("Gbahi", "Lazare", "peintre", "peinture générale", "Daloa", "Centre",
     "+225 05 77 88 99", "+225 05 77 88 99",
     "Peintre à Daloa. Intérieur, extérieur, ravalement. Équipe de 2 peintres.", 9, 12000, 250000,
     "par projet", 4.2, 17, True, ["Daloa"], ["Français", "Bété"], False),
     
    # Grand-Bassam
    ("Amani", "Kouadio", "carreleur", "pose carrelage", "Grand-Bassam", "Centre",
     "+225 07 88 99 00", "+225 07 88 99 00",
     "Carreleur à Grand-Bassam. Pose sol et mur, faïence. Travail soigné.", 8, 4500, 40000,
     "par m²", 4.4, 27, True, ["Grand-Bassam", "Abidjan"], ["Français"], False),
    ("Ekra", "Salomon", "jardinier", "entretien jardin", "Grand-Bassam", "Centre",
     "+225 01 99 00 11", "+225 01 99 00 11",
     "Jardinier à Grand-Bassam. Entretien espaces verts, tonte, taille, arrosage.", 7, 15000, 100000,
     "par intervention", 4.3, 19, True, ["Grand-Bassam", "Bingerville"], ["Français"], False),
     
    # Abidjan - Prestataires supplémentaires diverses catégories
    ("Koffi", "Arsène", "plombier", "urgences 24h", "Abidjan", "Zone 4",
     "+225 07 00 11 22", "+225 07 00 11 22",
     "Plombier urgentiste 24h/24. Fuite eau, canalisation bouchée. Intervention en moins d'1h sur Abidjan.", 13, 20000, 100000,
     "par intervention", 4.8, 56, True, ["Zone 4", "Marcory", "Treichville", "Plateau", "Cocody"], ["Français"], True),
    ("Gnonsoa", "Julien", "informatique", "sécurité informatique", "Abidjan", "Plateau",
     "+225 05 11 22 33", "+225 05 11 22 33",
     "Expert cybersécurité. Audit sécurité, antivirus entreprise, formation, protection données. Certifié CEH.", 10, 50000, 1000000,
     "par mission", 4.9, 38, True, ["Plateau", "Cocody", "Zone 4"], ["Français", "Anglais"], True),
    ("Yebouet", "Irène", "nettoyage", "nettoyage piscine", "Abidjan", "Cocody",
     "+225 07 22 33 44", "+225 07 22 33 44",
     "Entretien et nettoyage piscines. Traitement eau, nettoyage fond, maintenance pompe filtre. Contrats mensuels.", 11, 30000, 150000,
     "par intervention", 4.7, 44, True, ["Cocody", "Riviera", "Deux-Plateaux", "Angré"], ["Français"], True),
    ("Assoumou", "Valentin", "mecanicien", "carrosserie et peinture auto", "Abidjan", "Adjamé",
     "+225 05 33 44 55", "+225 05 33 44 55",
     "Carrossier peintre auto. Débosselage, redressage, peinture complète ou partielle. Toutes marques. Devis gratuit.", 14, 30000, 500000,
     "par intervention", 4.6, 71, True, ["Adjamé", "Abobo", "Yopougon", "Plateau"], ["Français"], True),
    ("Tape", "Léontine", "traiteur", "livraison repas domicile", "Abidjan", "Yopougon",
     "+225 07 44 55 66", "+225 07 44 55 66",
     "Cuisine maison livrée à domicile. Menu du jour, commandes spéciales, sauce tomate, foutou, attiéké. Livraison Yopougon et environs.", 5, 1500, 5000,
     "par repas", 4.8, 287, True, ["Yopougon", "Abobo", "Adjamé"], ["Français", "Dioula"], False),
    ("Ouédraogo", "Habib", "demenagement", "déménagement international", "Abidjan", "Plateau",
     "+225 07 55 66 77", "+225 07 55 66 77",
     "Déménagement local et international. Emballage professionnel, conteneurs, transit douanier. Vers Burkina, Mali, Sénégal, France.", 17, 200000, 5000000,
     "par déménagement", 4.7, 34, True, ["Abidjan", "International"], ["Français", "Mooré", "Anglais"], True),
    ("Zié", "Ange", "couture", "styliste créateur", "Abidjan", "Deux-Plateaux",
     "+225 01 66 77 88", "+225 01 66 77 88",
     "Styliste créateur. Collections prêt-à-porter africain, tenues événementielles, shooting photo. Marque propre 'Zié Créations'.", 7, 30000, 300000,
     "par tenue", 4.9, 112, True, ["Deux-Plateaux", "Cocody", "Plateau"], ["Français"], True),
    ("Dié", "Bénédicte", "coiffeur", "soins cheveux naturels", "Abidjan", "Cocody",
     "+225 07 77 88 99", "+225 07 77 88 99",
     "Spécialiste soins cheveux naturels afro. Transition capillaire, soins kératine, hydratation. Produits 100% naturels et bio.", 9, 10000, 60000,
     "par soin", 5.0, 231, True, ["Cocody", "Deux-Plateaux", "Riviera", "Angré"], ["Français"], True),
    ("Guédé", "Stéphanie", "nettoyage", "repassage et linge", "Abidjan", "Treichville",
     "+225 05 88 99 00", "+225 05 88 99 00",
     "Service repassage et entretien linge à domicile. Collecte et livraison possible. Chemises, costumes, robes. Rapide et soigné.", 4, 500, 5000,
     "par pièce", 4.6, 318, True, ["Treichville", "Marcory", "Port-Bouët", "Koumassi"], ["Français"], False),
    ("Bao", "Constant", "electricien", "panneau solaire", "Abidjan", "Yopougon",
     "+225 07 99 00 11", "+225 07 99 00 11",
     "Spécialiste énergie solaire. Installation panneaux, batteries lithium, onduleurs. Solutions autonomes pour maisons et entreprises.", 8, 100000, 3000000,
     "par installation", 4.8, 29, True, ["Yopougon", "Abobo", "Anyama", "Adjamé"], ["Français", "Dioula"], True),
    ("Gnanga", "Roméo", "macon", "piscine et VRD", "Abidjan", "Cocody",
     "+225 05 00 11 22", "+225 05 00 11 22",
     "Spécialiste construction piscines et voirie. Piscine enterrée, hors-sol, rénovation. Clôtures, allées, dallage extérieur.", 19, 500000, 10000000,
     "par projet", 4.9, 41, True, ["Cocody", "Riviera", "Deux-Plateaux", "Bingerville"], ["Français"], True),
    ("Nda", "Hubert", "informatique", "formation informatique", "Abidjan", "Plateau",
     "+225 07 11 22 33", "+225 07 11 22 33",
     "Formateur informatique. Cours particuliers Word, Excel, PowerPoint, Internet, comptabilité informatisée. À domicile ou en entreprise.", 14, 15000, 50000,
     "par séance", 4.7, 83, True, ["Plateau", "Cocody", "Deux-Plateaux", "Marcory"], ["Français"], False),
    ("Ettien", "Clémentine", "traiteur", "événements d'entreprise", "Abidjan", "Plateau",
     "+225 05 22 33 44", "+225 05 22 33 44",
     "Traiteur événements corporate. Cocktails, buffets, séminaires, team building. Service complet avec personnel et matériel. Sur devis.", 20, 10000, 5000,
     "par personne", 4.8, 58, True, ["Plateau", "Cocody", "Marcory", "Zone 4"], ["Français", "Anglais"], True),
    ("Kouamé", "Yvette", "couture", "broderie et décoration", "Abidjan", "Marcory",
     "+225 07 33 44 55", "+225 07 33 44 55",
     "Artisane broderie et décoration textile. Nappes, rideaux, coussins, vêtements brodés sur mesure. Travail traditionnel et moderne.", 11, 5000, 200000,
     "par projet", 4.6, 67, True, ["Marcory", "Treichville", "Zone 4"], ["Français"], False),
    ("Lobognon", "Patrick", "serrurier", "coffre-fort et sécurité", "Abidjan", "Plateau",
     "+225 01 44 55 66", "+225 01 44 55 66",
     "Spécialiste coffres-forts et sécurité physique. Vente, installation, réparation coffres. Blindage porte, serrures haute sécurité.", 16, 50000, 2000000,
     "par intervention", 4.7, 28, True, ["Plateau", "Cocody", "Marcory", "Zone 4"], ["Français"], True),
    ("Tuo", "Siaka", "mecanicien", "pneus et jantes", "Abidjan", "Adjamé",
     "+225 07 55 66 77", "+225 07 55 66 77",
     "Spécialiste pneumatiques. Vente pneus, équilibrage, géométrie, vidange. Toutes marques de pneus disponibles.", 13, 5000, 200000,
     "par intervention", 4.5, 94, True, ["Adjamé", "Plateau", "Abobo", "Yopougon"], ["Français", "Sénoufo"], False),
    ("Mahan", "Rosine", "coiffeur", "perruques et extensions", "Abidjan", "Treichville",
     "+225 05 66 77 88", "+225 05 66 77 88",
     "Spécialiste perruques, extensions et tissages. Pose, entretien, personnalisation. Cheveux naturels et synthétiques. Livraison possible.", 7, 10000, 100000,
     "par prestation", 4.8, 176, True, ["Treichville", "Marcory", "Adjamé", "Yopougon"], ["Français"], True),
    ("Gondo", "Fabrice", "climatisation", "climatisation voiture", "Abidjan", "Adjamé",
     "+225 07 77 88 99", "+225 07 77 88 99",
     "Technicien climatisation automobile. Recharge gaz, réparation compresseur, entretien clim voiture. Toutes marques.", 9, 15000, 80000,
     "par intervention", 4.4, 53, True, ["Adjamé", "Plateau", "Abobo", "Yopougon"], ["Français", "Dioula"], False),
    ("Aka", "Narcisse", "jardinier", "paysagiste professionnel", "Abidjan", "Riviera",
     "+225 01 88 99 00", "+225 01 88 99 00",
     "Paysagiste diplômé. Conception jardins, bassins, fontaines, éclairage extérieur, arrosage automatique. Réalisations haut de gamme.", 16, 100000, 5000000,
     "par projet", 4.9, 47, True, ["Riviera", "Cocody", "Angré", "Bingerville"], ["Français", "Anglais"], True),
]

insert_query = """
    INSERT INTO prestataires (
        nom, prenom, categorie, sous_categorie, ville, quartier,
        telephone, whatsapp, description, experience_annees,
        tarif_min, tarif_max, unite_tarif, note_moyenne, nb_avis,
        disponible, zone_intervention, langues, verified
    ) VALUES (
        %s, %s, %s, %s, %s, %s,
        %s, %s, %s, %s,
        %s, %s, %s, %s, %s,
        %s, %s, %s, %s
    )
"""

print("=" * 55)
print("  INSERTION — Prestataires de services CI")
print(f"  {len(PRESTATAIRES)} prestataires à insérer")
print("=" * 55)

inseres = 0

for p in PRESTATAIRES:
    try:
        cur.execute(insert_query, p)
        inseres += 1
        print(f"  ✅ {p[1]} {p[0]} — {p[2]} — {p[5]}")
    except Exception as e:
        print(f"  ❌ Erreur : {e}")

conn.commit()
cur.close()
conn.close()

print(f"\n{'=' * 55}")
print(f"  ✅ {inseres} prestataires insérés avec succès")
print(f"{'=' * 55}")
